esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}-hotspot
    password: !secret hotspot_password

logger:

api:

ota:

i2c:
  scl: D1
  sda: D2
  scan: true

button:
- platform: restart
  name: "${device_name}-reset"