display:
- platform: ssd1306_i2c
  id: oled_display
  model: SSD1306 128x32
  # model: SSD1306 128x64
  rotation: ${display_rotation}
  address: 0x3C
  pages:
    - id: display_page_empty
      lambda: |-
        it.fill(COLOR_OFF);
    - id: display_page_1
      lambda: |-
        it.printf(0, 0, id(font1), TextAlign::TOP_LEFT, "OpenDomus");
        it.strftime(128, 0, id(font1), TextAlign::TOP_RIGHT, "%H:%M", id(display_time).now());
        if (id(temperature_sensor).has_state()) {
          it.printf(0, 16, id(font1), TextAlign::TOP_LEFT, "T %.1f", id(temperature_sensor).state);
        }
        if (id(humidity_sensor).has_state()) {
          it.printf(128, 16, id(font1), TextAlign::TOP_RIGHT, "H %.0f%%", id(humidity_sensor).state);
        }
        it.line(0,0,127,0);
        it.line(0,0,0,31);
        it.line(0,31,127,31);
        it.line(127,0,127,31);

time:
- platform: homeassistant
  # timezone: Europe/Rome
  id: display_time

font:
- file: font/retrogaming.ttf
  id: font1
  size: 11
  glyphs: '!"%*()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'