display:
- platform: ssd1306_i2c
  model: SSD1306 128x32
  rotation: ${display_rotation}
  address: 0x3C
  lambda: |-
    it.printf(0, 0, id(font1), TextAlign::TOP_LEFT, "OpenDomus");
    it.strftime(128, 0, id(font1), TextAlign::TOP_RIGHT, "%H:%M", id(display_time).now());
    if (id(display_temperature).has_state()) {
      it.printf(0, 16, id(font1), TextAlign::TOP_LEFT, "T %.1f", id(display_temperature).state);
    }
    if (id(display_humidity).has_state()) {
      it.printf(128, 16, id(font1), TextAlign::TOP_RIGHT, "H %.0f%%", id(display_humidity).state);
    }
    if (id(display_motion).state) {
      it.printf(64, 16, id(font1), TextAlign::TOP_CENTER, "(*)");
    }

time:
- platform: homeassistant
  timezone: Europe/Rome
  id: display_time

font:
- file: font/retrogaming.ttf
  id: font1
  size: 11
  glyphs: '!"%*()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
