apds9960:
  address: 0x39

sensor:
- platform: apds9960
  type: PROXIMITY
  name: "${device_name}-proximity"
  id: proximity_sensor
  filters:
    - calibrate_linear:
      - 3 -> 0
      - 20 -> 100
    - clamp:
        min_value: 0
        max_value: 100  
- platform: apds9960
  type: CLEAR
  name: "${device_name}-ambient-light"
  id: ambient_light_sensor

binary_sensor:
- platform: apds9960
  direction: UP
  name: "${device_name}-gesture-up"
- platform: apds9960
  direction: DOWN
  name: "${device_name}-gesture-down"
- platform: apds9960
  direction: LEFT
  name: "${device_name}-gesture-left"
- platform: apds9960
  direction: RIGHT
  name: "${device_name}-gesture-right"