sensor:
- platform: adc
  pin: A0
  name: "${device_name}-illuminance"
  device_class: illuminance
  unit_of_measurement: lx
  accuracy_decimals: 0
  update_interval: 120s
  filters:
  - lambda: |-
      return (x / 10000.0) * 2000000.0;