sensor:
- platform: sht3xd
  temperature:
    name: "${device_name}-temperature"
    id: temperature_sensor
    filters:
      - median:
          window_size: 10
          send_every: 2
          send_first_at: 2
      - calibrate_linear:
          datapoints:
            # sensor -> true value
            - 0.0 -> 0.0
            - 22.5 -> 20.0
  humidity:
    name: "${device_name}-humidity"
    id: humidity_sensor
    filters:
      - median:
          window_size: 10
          send_every: 2
          send_first_at: 2
  address: 0x44
  update_interval: 30s