sensor:
- platform: sht3xd
  temperature:
    name: "${device_name}-temperature"
    id: temperature_sensor
    filters:
    - sliding_window_moving_average:
        window_size: 12
        send_every: 8
        send_first_at: 8
  humidity:
    name: "${device_name}-humidity"
    id: humidity_sensor
    filters:
    - sliding_window_moving_average:
        window_size: 12
        send_every: 8
        send_first_at: 8
  address: 0x44
  update_interval: 15s