sensor:
- platform: sht3xd
  temperature:
    name: "${device_name}-temperature"
    id: temperature_sensor
  humidity:
    name: "${device_name}-humidity"
    id: humidity_sensor
  address: 0x44
  update_interval: 15s