substitutions:
  device_name: your-device-name

# You can comment out the lines of the modules you are not using.
packages:
  common: !include modules_s2mini/common.yml
  display: !include modules_common/display_128x32.yml
  # display: !include modules_common/display_128x64.yml
  rgb_leds: !include modules_s2mini/rgb_leds.yml
  buzzer: !include modules_s2mini/buzzer.yml
  relay: !include modules_s2mini/relay.yml
  temp_sensor: !include modules_common/temp_sensor.yml
  # gesture_sensor: !include modules_common/gesture_sensor.yml
  light_sensor: !include modules_common/light_sensor.yml
  motion_sensor: !include modules_s2mini/motion_sensor.yml
  ir_remote: !include modules_s2mini/ir_remote.yml
  buttons: !include modules_s2mini/buttons.yml

# Automations: uncomment the ones you want to activate.
  display_motion: !include automations/display_motion.yml
  motion_status_leds: !include automations/motion_status_leds.yml