substitutions:
  device_name: your-device-name
  display_rotation: "180"

# You can comment out the lines of the modules you are not using.
packages:
  common: !include modules/common.yml
  display: !include modules/display.yml
  rgb_leds: !include modules/rgb_leds.yml
  buzzer: !include modules/buzzer.yml
  relay: !include modules/relay.yml
  temp_sensor: !include modules/temp_sensor.yml
  # gesture_sensor: !include modules/gesture_sensor.yml
  light_sensor: !include modules/light_sensor.yml
  motion_sensor: !include modules/motion_sensor.yml
  ir_remote: !include modules/ir_remote.yml

# Automations: uncomment the ones you want to activate.
  display_motion: !include automations/display_motion.yml
  motion_status_leds: !include automations/motion_status_leds.yml