switch:
  - platform: template
    name: "${device_name}-motion-display"
    id: motion_display_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG
    turn_off_action:
      - script.execute: show_page_empty  # clear screen when disabling

binary_sensor:
  - id: !extend motion_sensor
    on_press:
      - if:
          condition:
            switch.is_on: motion_display_switch
          then:
            - script.execute: show_page_readout
    on_release:
      - if:
          condition:
            switch.is_on: motion_display_switch
          then:
            - script.execute: show_page_empty