switch:
  - platform: template
    name: "${device_name}-motion-leds"
    id: motion_leds_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: CONFIG
    turn_off_action:
      - light.addressable_set:
          id: rgb_leds
          range_from: 0
          range_to: 1
          red: 0%
          green: 0%
          blue: 0%

binary_sensor:
- id: !extend moving_target_sensor
  on_press:
    - if:
        condition:
          switch.is_on: motion_leds_switch
        then:
          - light.addressable_set:
              id: rgb_leds
              range_from: 0
              range_to: 0
              red: 100%
              green: 0%
              blue: 0%
              color_brightness: 20%
  on_release:
    - if:
        condition:
          switch.is_on: motion_leds_switch
        then:
          - light.addressable_set:
              id: rgb_leds
              range_from: 0
              range_to: 0
              red: 0%
              green: 0%
              blue: 0%
- id: !extend still_target_sensor
  on_press:
    - if:
        condition:
          switch.is_on: motion_leds_switch
        then:
          - light.addressable_set:
              id: rgb_leds
              range_from: 1
              range_to: 1
              red: 0%
              green: 100%
              blue: 0%
              color_brightness: 20%
  on_release: 
    - if:
        condition:
          switch.is_on: motion_leds_switch
        then:
          - light.addressable_set:
              id: rgb_leds
              range_from: 1
              range_to: 1
              red: 0%
              green: 0%
              blue: 0%